title: integer-classifier
hero_image: images/banner.png
description: integer-classifier description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-29"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
