title: integer-classifier
hero_image: images/banner.png
description: integer-classifier description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-29"
steps:
  - title: Introduction
  - title: Get some training data
  - title: Explore and prepare your data
  - title: Build your model
  - title: Compile your model
  - title: Train your model
  - title: Test your model
  - title: What's next?
